# This is a basic workflow to help you get started with Actions

name: Document generation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docgen:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@1.9.4
        with:
          # Path to Doxyfile
          doxyfile-path: './.github/Doxyfile1'
          # Working directory
          working-directory: './'
          # Generate latex documentation
          enable-latex: false
          # Extra alpine packages for the build environment
          #additional-packages: # optional, default is
      - name: Upload output directory
        uses: actions/upload-artifact@v2
        with:
          name: doc-files
          path: docs
          retention-days: 1

  copy:
    runs-on: ubuntu-latest
    needs: docgen
    steps:
      - uses: actions/checkout@v3
        with:
          ref: fdc_bitstream
      - name: Download output directory
        uses: actions/download-artifact@v2
        with:
          name: doc-files
          path: docs
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          #author_name: yas-sim
          #author_email: yasu0710@gmail.com
          message: 'Update docs'
          branch: master
          add: 'docs/html/*'

